#CDNの利用
source 'https://cdn.jsdelivr.net/cocoa/'

#Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

def common
  pod 'SwiftGen', '~> 6.0'
  pod 'SwiftLint'
end

target 'GenerambaTemplates' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  common
  pod 'SwiftFormat/CLI'
  
  target'UIComponent' do
    common
  end

  target 'GenerambaTemplatesTests' do
    inherit! :search_paths
  end
end

